# Generated by Django 4.1 on 2024-05-28 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "place_id",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                ("place_name", models.CharField(max_length=100)),
                (
                    "place_type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "식사"), (2, "카페"), (3, "숙박"), (4, "관광")]
                    ),
                ),
                ("place_time", models.PositiveSmallIntegerField()),
                ("place_latitude", models.DecimalField(decimal_places=6, max_digits=8)),
                (
                    "place_longitude",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                ("plan_id", models.AutoField(primary_key=True, serialize=False)),
                ("plan_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "tag_id",
                    models.PositiveSmallIntegerField(primary_key=True, serialize=False),
                ),
                ("tag_name", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Traveler",
            fields=[
                (
                    "trvlr_id",
                    models.PositiveSmallIntegerField(primary_key=True, serialize=False),
                ),
                ("trvlr_email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                ("trip_id", models.AutoField(primary_key=True, serialize=False)),
                ("trip_start", models.DateField()),
                ("trip_end", models.DateField()),
                (
                    "trip_state",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "예정"), (2, "진행중"), (3, "완료")]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TripTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PlanT_Backend.tag",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PlanT_Backend.trip",
                    ),
                ),
            ],
            options={
                "unique_together": {("trip", "tag")},
            },
        ),
        migrations.AddField(
            model_name="trip",
            name="trip_tag",
            field=models.ManyToManyField(
                through="PlanT_Backend.TripTag", to="PlanT_Backend.tag"
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="trip_traveler",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="PlanT_Backend.traveler"
            ),
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                ("route_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "route_end",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_end_place",
                        to="PlanT_Backend.place",
                    ),
                ),
                (
                    "route_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PlanT_Backend.plan",
                    ),
                ),
                (
                    "route_start",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_start_place",
                        to="PlanT_Backend.place",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="plan",
            name="plan_trip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="PlanT_Backend.trip"
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="place_tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="PlanT_Backend.tag"
            ),
        ),
    ]
