# Generated by Django 4.1 on 2024-05-28 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PlanT_Backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="traveler",
            name="trvlr_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
