# Generated by Django 4.1 on 2024-04-15 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PlanT_Backend", "0002_alter_plan_plan_id_alter_route_route_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trip",
            old_name="trip_posstime",
            new_name="trip_walkposstime",
        ),
        migrations.AddField(
            model_name="trip",
            name="trip_cycleposstime",
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
