# Generated by Django 4.1 on 2024-05-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PlanT_Backend", "0005_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
